"""Project-only full-pool reviewer; legacy Only_codes HTML stays untouched."""

HTML = r'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>COMPAG r92 full-pool review</title>
<style>
:root{color-scheme:dark;font:14px system-ui,sans-serif;background:#0b1522;color:#eef5ff}*{box-sizing:border-box}body{margin:0}header{padding:12px 16px;background:#14243a;border-bottom:1px solid #35506d}h1{margin:0 0 4px;font-size:20px}.note{color:#b8cce3}nav{display:flex;flex-wrap:wrap;gap:9px;align-items:end;padding:12px 16px;background:#102035}label{display:flex;flex-direction:column;gap:3px;font-size:12px}select,button,input{font:inherit;background:#223a56;color:#fff;border:1px solid #5a7695;border-radius:5px;padding:5px}button{cursor:pointer}button:hover{background:#365b84}.checks{display:flex;gap:12px;align-items:center}.checks label{flex-direction:row;align-items:center}main{display:grid;grid-template-columns:minmax(0,2fr) minmax(360px,1fr);height:calc(100vh - 205px);min-height:470px}.image{position:relative;background:#000;overflow:hidden}canvas{width:100%;height:100%;cursor:crosshair}.side{padding:10px;overflow:auto;border-left:1px solid #35506d}#counts,#chosen,#message{white-space:pre-wrap;font-family:ui-monospace,monospace;font-size:12px;margin:7px 0}table{width:100%;border-collapse:collapse;font-size:12px}th,td{padding:4px;border-bottom:1px solid #30455d;text-align:left}tbody tr{cursor:pointer}tbody tr:hover,.selected{background:#30587a}.actions{display:flex;flex-wrap:wrap;gap:5px;padding:8px 0}.foot{display:flex;gap:8px;align-items:center}#list{max-height:36vh;overflow:auto}.warn{color:#ffd890}@media(max-width:850px){main{display:block;height:auto}.image{height:50vh}.side{height:55vh}}
</style></head><body>
<header><h1>COMPAG r92 · full scored pool</h1><div class="note">Every valid scored candidate is selectable. The Top-K shortlist is a recommendation. Filters affect the view only; saving a decision uses the stable candidate key. Deleted masks leave the active pool and downstream outputs; their original score remains for audit. Wheel to zoom; drag with either mouse button to move the image.</div></header>
<nav>
<label>Card <select id="base"></select></label>
<label>Prediction source <select id="basis"><option value="effective">Effective machine decision</option><option value="raw">Raw XGBoost</option></select></label>
<label>Predicted class <select id="pred"><option value="all">All</option><option value="cj">Model CJ</option><option value="noncj">Model non-CJ</option></select></label>
<label>Model difficulty <select id="hard"><option value="all">All</option><option value="inside">Within margin</option><option value="outside">Outside margin</option></select></label>
<label>Acquisition <select id="shortlist"><option value="all">All candidates</option><option value="in">In actual shortlist</option><option value="out">Outside shortlist</option></select></label>
<label>Review status <select id="status"><option value="all">All</option><option value="unreviewed">No decision</option><option value="confident">Individual decision</option><option value="human_uncertain">Human-uncertain decision</option><option value="bulk_accepted">Bulk accepted prediction</option><option value="skipped">Skipped</option><option value="deleted">Deleted</option></select></label>
<label>Human label <select id="human"><option value="all">All</option><option value="cj">Human CJ</option><option value="noncj">Human non-CJ</option><option value="none">No effective label</option></select></label>
<div class="checks"><label><input id="mismatch" type="checkbox"> Mismatches only</label><label><input id="hide_seen" type="checkbox"> Hide seen</label><label><input id="hide_deleted" type="checkbox" checked> Hide deleted</label></div>
<button id="reset">Reset filters / All</button>
</nav>
<main><div class="image"><canvas id="canvas"></canvas></div><div class="side"><div id="counts"></div><div id="chosen">Select a candidate from the image or list.</div><div class="actions"><button data-action="accept">Accept</button><button data-action="flip">Flip</button><button data-action="sus_accept">Uncertain accept</button><button data-action="sus_flip">Uncertain flip</button><button data-action="skip">Skip</button><button data-action="delete">Delete mask</button><button data-action="unsee">Unsee</button><button data-action="undo">Undo last event</button></div><div class="actions"><button id="accept_remaining">Preview / accept remaining model predictions</button><button data-action="undo_bulk">Undo last batch</button></div><div id="message"></div><div class="foot"><button id="previous">Previous page</button><span id="page"></span><button id="next">Next page</button></div><div id="list"><table><thead><tr><th>Tile</th><th>ID</th><th>Machine</th><th>p_ui</th><th>Hard</th><th>Top-K</th><th>Review</th></tr></thead><tbody id="rows"></tbody></table></div><p class="note">Accept remaining covers all cards in this scored pool, independent of filters and seen state. It records model predictions as bulk accepted labels, distinct from masks reviewed one by one. Deleted and skipped masks are excluded. Shortlist membership comes from the bound selection CSV.</p></div></main>
<script nonce="__NONCE__">
const TOKEN='__TOKEN__', Q=id=>document.getElementById(id);let data=null,items=[],shown=[],selected=null,page=0,photo=new Image(),zoom=1,offset=[0,0],drag=null;const cv=Q('canvas'),ctx=cv.getContext('2d'),PAGE=80;
async function api(path,body){const r=await fetch(path,{method:body?'POST':'GET',headers:{'X-Review-Token':TOKEN,'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined});return r.json()}
function val(id){return Q(id).value}function hard(it){return val('basis')==='raw'?it.raw_xgb_hard:it.uncertain}function prediction(it){return val('basis')==='raw'?it.raw_xgb_pred:it.pred}
function match(it){if(val('pred')!=='all'&&prediction(it)!==(val('pred')==='cj'?1:0))return false;if(val('hard')!=='all'&&hard(it)!==(val('hard')==='inside'))return false;if(val('shortlist')!=='all'&&it.shortlisted!==(val('shortlist')==='in'))return false;if(val('status')!=='all'&&it.review_status!==val('status'))return false;if(val('human')!=='all'&&(val('human')==='none'?it.human!==null:it.human!==(val('human')==='cj'?1:0)))return false;if(Q('hide_seen').checked&&it.seen)return false;if(Q('hide_deleted').checked&&it.review_status==='deleted')return false;if(Q('mismatch').checked&&!(it.human!==null&&it.human!==prediction(it)))return false;return true}
function desc(it){return `${it.key}\nEffective machine=${it.pred?'CJ':'non-CJ'} · raw XGB=${it.raw_xgb_pred?'CJ':'non-CJ'} · score source=${it.score_source}\np_ui=${fmt(it.p_ui)} · threshold=${fmt(it.thr_eff)} · margin=${fmt(data.params.al_margin)} · distance=${fmt(it.boundary_distance)}\nraw XGB p=${fmt(it.xgb_p)} · raw distance=${fmt(Math.abs(it.xgb_p-data.params.thr_xgb))}\nShortlist=${it.shortlisted?'rank '+it.shortlist_rank+' ('+it.shortlist_reason+')':'outside'} · status=${it.review_status} · human=${it.human===null?'none':it.human?'CJ':'non-CJ'} · seen=${it.seen}\nGeometry=${it.geometry}`}
function fmt(x){return x===null||x===undefined?'NA':typeof x==='number'?x.toFixed(4):String(x)}
function center(it){const xs=it.xs.slice(0,-1),ys=it.ys.slice(0,-1);return[(Math.min(...xs)+Math.max(...xs))/2,(Math.min(...ys)+Math.max(...ys))/2]}
function render(){shown=items.filter(match);page=Math.min(page,Math.max(0,Math.ceil(shown.length/PAGE)-1));const reviewed=items.filter(x=>x.review_status!=='unreviewed').length,hardN=items.filter(hard).length,shortN=items.filter(x=>x.shortlisted).length;
 Q('counts').textContent=`Scored pool (all cards): ${data.pool_count} · current card: ${items.length} · active on this card: ${items.filter(x=>x.review_status!=='deleted').length}\nFiltered on this card: ${shown.length} · model-hard: ${hardN} · actual shortlist: ${shortN}\nTerminal review events: ${reviewed} · deleted: ${items.filter(x=>x.review_status==='deleted').length} · bulk accepted: ${items.filter(x=>x.review_status==='bulk_accepted').length} · seen: ${items.filter(x=>x.seen).length}\nActive filters: ${['basis','pred','hard','shortlist','status','human'].map(k=>k+'='+val(k)).join(', ')} · hide seen=${Q('hide_seen').checked} · hide deleted=${Q('hide_deleted').checked} · mismatch=${Q('mismatch').checked}`;
 Q('page').textContent=`${shown.length? page+1:0}/${Math.ceil(shown.length/PAGE)} · ${shown.length} matches`;Q('previous').disabled=page===0;Q('next').disabled=(page+1)*PAGE>=shown.length;
 const tbody=Q('rows');tbody.replaceChildren();for(const it of shown.slice(page*PAGE,(page+1)*PAGE)){const tr=document.createElement('tr');if(it.key===selected)tr.className='selected';for(const v of [it.image.replace(/^.*_(y\d+x\d+).*$/,'$1'),it.id,prediction(it)?'CJ':'non-CJ',fmt(val('basis')==='raw'?it.xgb_p:it.p_ui),hard(it)?'Yes':'No',it.shortlisted?'#'+it.shortlist_rank:'Outside',it.review_status]){const td=document.createElement('td');td.textContent=v;tr.appendChild(td)}tr.onclick=()=>{selected=it.key;render()};tbody.appendChild(tr)}
 const chosen=items.find(x=>x.key===selected);Q('chosen').textContent=chosen?desc(chosen):'Select a candidate from the image or list.';draw()}
function draw(){const bounds=cv.getBoundingClientRect();cv.width=Math.max(1,bounds.width*devicePixelRatio);cv.height=Math.max(1,bounds.height*devicePixelRatio);ctx.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0);ctx.fillStyle='#000';ctx.fillRect(0,0,bounds.width,bounds.height);if(!photo.complete||!photo.naturalWidth)return;let s=Math.min(bounds.width/photo.width,bounds.height/photo.height)*zoom;ctx.setTransform(s*devicePixelRatio,0,0,s*devicePixelRatio,offset[0]*devicePixelRatio,offset[1]*devicePixelRatio);ctx.drawImage(photo,0,0);for(const it of shown){ctx.beginPath();for(let j=0;j<it.xs.length;j++)j?ctx.lineTo(it.xs[j],it.ys[j]):ctx.moveTo(it.xs[j],it.ys[j]);ctx.strokeStyle=it.key===selected?'#fff':it.shortlisted?'#ffe155':prediction(it)?'#47ff6a':'#ff6e6e';ctx.lineWidth=(it.key===selected?4:2)/s;ctx.stroke();const c=center(it);ctx.beginPath();ctx.arc(c[0],c[1],4/s,0,7);ctx.fillStyle=ctx.strokeStyle;ctx.fill()}}
async function load(){const requested=val('base');const d=await api('/api/state?base='+encodeURIComponent(requested));if(d.error){Q('message').textContent=d.error;return}const previousBase=data?.base;data=d;items=d.items;const b=Q('base');if(!b.options.length)for(const base of d.bases){let opt=document.createElement('option');opt.value=opt.textContent=base;b.appendChild(opt)}b.value=d.base;if(previousBase!==d.base){const nextPhoto=new Image();photo=nextPhoto;nextPhoto.onload=()=>{if(photo!==nextPhoto)return;zoom=1;const bounds=cv.getBoundingClientRect(),s=Math.min(bounds.width/photo.width,bounds.height/photo.height);offset=[(bounds.width-photo.width*s)/2,(bounds.height-photo.height*s)/2];render()};nextPhoto.src='/mosaic?base='+encodeURIComponent(d.base)+'&token='+TOKEN}render()}
for(const id of ['basis','pred','hard','shortlist','status','human','mismatch','hide_seen','hide_deleted'])Q(id).onchange=()=>{page=0;render()};Q('base').onchange=()=>{selected=null;page=0;load()};Q('reset').onclick=()=>{for(const id of ['basis','pred','hard','shortlist','status','human'])Q(id).selectedIndex=0;Q('mismatch').checked=false;Q('hide_seen').checked=false;Q('hide_deleted').checked=false;page=0;render()};Q('previous').onclick=()=>{page--;render()};Q('next').onclick=()=>{page++;render()};
document.querySelectorAll('[data-action]').forEach(button=>button.onclick=async()=>{const action=button.dataset.action;if(!selected&&!['undo','undo_bulk'].includes(action)){Q('message').textContent='Select a candidate first.';return}if(action==='delete'&&!confirm(`Delete this mask from the active pool and downstream training/export?\n${selected}`))return;const result=await api('/api/action',{action,key:selected,base:data.base});Q('message').textContent=result.msg||result.error||'';await load()});
Q('accept_remaining').onclick=async()=>{const plan=await api('/api/bulk-plan');if(plan.error){Q('message').textContent=plan.error;return}Q('message').textContent=`Remaining across all cards: ${plan.remaining_count} (model CJ=${plan.model_cj_count}, model non-CJ=${plan.model_noncj_count}). Existing decisions, deleted and skipped masks stay unchanged.`;if(!plan.remaining_count)return;if(!confirm(`Accept the recorded model predictions for ${plan.remaining_count} undecided masks across ALL cards?\nCJ=${plan.model_cj_count}, non-CJ=${plan.model_noncj_count}.\nThis is a bulk model acceptance, not individual inspection.`))return;const result=await api('/api/action',{action:'accept_remaining',expected_count:plan.remaining_count,expected_log_sha256:plan.review_log_sha256});Q('message').textContent=result.msg||result.error||'';await load()};
cv.onclick=e=>{if(e.button!==0||drag?.moved)return;const r=cv.getBoundingClientRect(),s=Math.min(r.width/photo.width,r.height/photo.height)*zoom,x=(e.clientX-r.left-offset[0])/s,y=(e.clientY-r.top-offset[1])/s;let best=null,dist=Infinity;for(const it of shown){const c=center(it),d=(c[0]-x)**2+(c[1]-y)**2;if(d<dist){best=it;dist=d}}if(best&&dist<(30/s)**2){selected=best.key;render()}};
cv.onwheel=e=>{e.preventDefault();zoom=Math.max(.3,Math.min(8,zoom*(e.deltaY<0?1.12:1/1.12)));draw()};
cv.oncontextmenu=e=>{e.preventDefault()};
cv.onmousedown=e=>{if(e.button!==0&&e.button!==2)return;if(e.button===2)e.preventDefault();drag={button:e.button,x:e.clientX,y:e.clientY,ox:offset[0],oy:offset[1],moved:false}};
window.onmousemove=e=>{if(!drag||!(e.buttons&(drag.button===2?2:1)))return;const dx=e.clientX-drag.x,dy=e.clientY-drag.y;drag.moved=Math.abs(dx)+Math.abs(dy)>4;offset=[drag.ox+dx,drag.oy+dy];draw()};
window.onmouseup=e=>{if(drag&&e.button===drag.button)setTimeout(()=>drag=null,0)};window.onblur=()=>{drag=null};window.onresize=draw;load();
</script></body></html>'''
